CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
cash VARCHAR(100) NOT NULL,
reserve VARCHAR(100) NOT NULL,
);
CREATE TABLE IF NOT EXISTS servises(
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
cost VARCHAR(100) NOT NULL,
);
CREATE TABLE IF NOT EXISTS orders(
id SERIAL PRIMARY KEY,
userid INTEGER REFERENCES users (id),
serviseid INTEGER REFERENCES servises (id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);